# to run this dockerfile: docker build -f Dockerfile.dev .
# -f specifies the dockerfile name
FROM node:lts-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]